- name: "Configure ranger"
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Basic configuration for ranger
    ansible.builtin.blockinfile:
      path: ~/.config/ranger/rc.conf
      block: |
        set show_hidden true
        set confirm_on_delete yes

        map DD shell gio trash %s
        map di console mkdir%space
        map N shell -dsp nautilus %d
        map T shell -dsp terminal
        map to console touch%space
  - name: Kitty
    ansible.builtin.blockinfile:
      path: ~/.config/kitty/kitty.conf
      block: |
        cursor_blink_interval 0
        enabled_layouts tall
        # term xterm-kitty
        term xterm-color
        include doom_vibrant.conf
  - name: Kitty colorscheme
    ansible.builtin.copy:
      src: ./files/doom_vibrant.conf
      dest: ~/.config/kitty/doom_vibrant.conf
  - name: Git
    ansible.builtin.blockinfile:
      path: ~/.gitconfig
      block: |
        [user]
            name = "Matthias Schaufelberger"
            email = "schaufim@gmail.com"
        [init]
            defaultBranch = main
        [commit]
            verbose = true
        [alias]
            lola = log --all --oneline --graph
        [push]
            autoSetupRemote = true
  - name: VSCodium
    ansible.builtin.blockinfile:
      path: ~/.config/VSCodium/User/settings.json 
      block: |
        {
            "workbench.colorTheme": "Default Dark Modern",
            "security.workspace.trust.untrustedFiles": "open",
            "keyboard.dispatch": "keyCode",
            "vim.gdefault": true,
            "vim.history": 1000,
            "vim.visualModeKeyBindings": [
                {
                    "before": [ "H" ],
                    "after": [ "0" ]
                },
                {
                    "before": [ "L" ],
                    "after": [ "$" ]
                }
            ],
            "vim.normalModeKeyBindings": [
                {
                    "before": [ "H" ],
                    "after": [ "0" ]
                },
                {
                    "before": [ "L" ],
                    "after": [ "$" ]
                }
            ],
            "vim.insertModeKeyBindings": [
                {
                  "before": ["j", "k"],
                  "after": ["<Esc>"]
                }
            ],
        }