- name: "Configure debian settings system-wide"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Systemd stop job 90s time limit"
      lineinfile: dest=/etc/systemd/system.conf regexp='^(.*)DefaultTimeoutStopSec(.*)' line='DefaultTimeoutStopSec=90s' state=present backup=yes
    - name: "Remove image magick security policy for eps"
      lineinfile: dest=/etc/ImageMagick-6/policy.xml regexp='^(.*)<policy domain="coder" .* pattern="EPS" />' line='  <policy domain="coder" rights="read|write" pattern="EPS" />' state=present backup=yes
    - name: "Remove image magick security policy for pdf"
      lineinfile: dest=/etc/ImageMagick-6/policy.xml regexp='^(.*)<policy domain="coder" .* pattern="PDF" />' line='  <policy domain="coder" rights="read|write" pattern="PDF" />' state=present backup=yes
    - name: "Remove gnome games preinstalled"
      ansible.builtin.apt:
        name:
        - iagno
        - lightsoff
        - four-in-a-row
        - gnome-robots
        - pegsolitaire
        - gnome-2048
        - hitori
        - gnome-klotski
        - gnome-mines
        - gnome-mahjongg
        - gnome-sudoku
        - quadrapassel
        - swell-foop
        - gnome-tetravex
        - gnome-taquin
        - aislerio
        state: absent
    - name: "Install general utilities"
      ansible.builtin.apt:
        name:
        - vlc
        - flatpak
        - gnome-software-plugin-flatpak
        - epiphany-browser
        - dosfstools
        - mtools
        - gparted
        - deborphan
        - pdftk
        - borgbackup
        - foliate
        - calibre
        - htop
        - neofetch
        - keepass2
        - gimp
        - inkscape
        state: present
    - name: "Install programming utilities"
      ansible.builtin.apt:
        name:
        - vim-gtk3
        - git
        - kitty
        - ranger
        - dconf-editor
        - emacs
        - python-is-python3
        - python3-pip
        - python3.11-venv
        - ack
        - fd-find
        state: present
# This takes forever
    - name: "Install LaTeX and pandoc stuff"
      ansible.builtin.apt:
        name:
        - texlive-full
        - latexmk
        - pandoc
        state: present
# Install sway
    - name: "Sway as a window manager"
      ansible.builtin.apt:
        name:
        - sway
        - swaylock
        - rofi
        - i3status
        state: present
