- name: "Configure debian settings"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Add aliases to bashrc"
      lineinfile: 
        dest: ~/.bashrc
        state: present 
        search_string: "{{ item.search_string }}"
        line: "{{ item.line }}"
      loop:
        - { search_string: "alias here='xdg-open .'", line: "alias here='xdg-open .'" }
        - { search_string: "alias fd=fdfind", line: "alias fd=fdfind" }
        - { search_string: "alias ytdl=.venv/ytdl/bin/youtube-dl", line: "alias ytdl=.venv/ytdl/bin/youtube-dl" }
    - name: "Creates systemd user directory"
      ansible.builtin.file:
        path: ~/.config/systemd/user
        state: directory
    - name: "Copy startup maintainer to systemd user directory"
      ansible.builtin.copy:
        src: ./systemd/startup_maintenance.service
        dest: ~/.config/systemd/user
    - name: "Copy borg backup to systemd user directory"
      ansible.builtin.copy:
        src: ./systemd/borg_backup.service
        dest: ~/.config/systemd/user
    - name: "Copy borg backup timer to systemd user directory"
      ansible.builtin.copy:
        src: ./systemd/borg_backup.timer
        dest: ~/.config/systemd/user
    - name: "Systemd - enable borg backup timer"
      ansible.builtin.systemd_service:
        name: borg_backup.timer
        enabled: true
        masked: no
        scope: user
    - name: "Systemd - enable systemd startup maintainer"
      ansible.builtin.systemd_service:
        name: startup_maintenance.service
        enabled: true
        masked: no
        scope: user
    - name: "Systemd - start startup maintainer"
      ansible.builtin.systemd_service:
        name: startup_maintenance.service
        state: started
        scope: user
    - name: "Create directory"
      ansible.builtin.file:
        path: ~/programs
        state: directory
    - name: "get z jump around"
      ansible.builtin.get_url: 
        url: "https://github.com/rupa/z/archive/refs/tags/v1.12.tar.gz"  
        dest: ~/programs
    - name: "extract z"
      ansible.builtin.unarchive:
        src: ~/programs/z-1.12.tar.gz
        dest: ~/programs
    - name: "Add z to bashrc"
      lineinfile: 
        dest: ~/.bashrc
        search_string: 'programs/z-1.12/z.sh' 
        line: '. ~/programs/z-1.12/z.sh' 
        state: present
    - name: "Create .venv directory for youtube-dl"
      ansible.builtin.file:
        path: ~/.venv/ytdl
        state: directory
    - name: "Create venv for ytdl"
      pip:
        # TODO This should not be the absolute path
        requirements: ~/scripts/ansible/files/ytdl_requirements.txt
        virtualenv: ~/.venv/ytdl
        virtualenv_command: /usr/bin/python3.11 -m venv
