---
- name: "Remove gnome games preinstalled"
  ansible.builtin.apt:
    name:
    - aislerio
    - four-in-a-row
    - gnome-2048
    - gnome-klotski
    - gnome-mahjongg
    - gnome-mines
    - gnome-robots
    - gnome-sudoku
    - gnome-taquin
    - gnome-tetravex
    - hitori
    - iagno
    - lightsoff
    - pegsolitaire
    - quadrapassel
    - swell-foop
    state: absent
  become: true

- name: "Install general utilities"
  ansible.builtin.apt:
    name:
    - borgbackup
    - calibre
    - deborphan
    - dosfstools
    - epiphany-browser
    - flatpak
    - foliate
    - gimp
    - gnome-software-plugin-flatpak
    - gparted
    - htop
    - inkscape
    - keepass2
    - mtools
    - neofetch
    - pdftk
    - vlc
    state: present
  become: true

- name: "Extensions"
  ansible.builtin.apt:
    name:
    - gnome-shell-extensions
    state: present
  become: true

- name: "Install programming utilities"
  ansible.builtin.apt:
    name:
    - ack
    - bash-completion
    - dconf-editor
    - emacs
    - exuberant-ctags
    - fd-find
    - latexmk
    - pandoc
    - pylint
    - python3.11-venv
    - python3-pip
    - python-is-python3
    - rsync
    - shellcheck
    - texlive-full
    state: present
  become: true

- name: "Add contrib repository for multimedia encryption codecs"
  ansible.builtin.shell:
    cmd: apt-add-repository contrib
  become: true

- name: "Print information about reconfiguring"
  ansible.builtin.debug:
    msg: "For multimedia codects, you might need to do perform the following action: sudo dpkg-reconfigure libdvd-pkg"

- name: "Remove image magick security policy for eps"
  ansible.builtin.lineinfile: 
    dest: /etc/ImageMagick-6/policy.xml 
    regexp: '^(.*)<policy domain="coder" .* pattern="EPS" />' 
    line: '  <policy domain="coder" rights="read|write" pattern="EPS" />' 
    state: present 
    backup: yes
  become: true

- name: "Remove image magick security policy for pdf"
  ansible.builtin.lineinfile: 
    dest: /etc/ImageMagick-6/policy.xml 
    regexp: '^(.*)<policy domain="coder" .* pattern="PDF" />' 
    line: '  <policy domain="coder" rights="read|write" pattern="PDF" />' 
    state: present 
    backup: yes
  become: true
