---
- name: "Remove gnome games preinstalled"
  ansible.builtin.apt:
    name:
    - iagno
    - lightsoff
    - four-in-a-row
    - gnome-robots
    - pegsolitaire
    - gnome-2048
    - hitori
    - gnome-klotski
    - gnome-mines
    - gnome-mahjongg
    - gnome-sudoku
    - quadrapassel
    - swell-foop
    - gnome-tetravex
    - gnome-taquin
    - aislerio
    state: absent
  become: true
- name: "Install general utilities"
  ansible.builtin.apt:
    name:
    - vlc
    - flatpak
    - gnome-software-plugin-flatpak
    - epiphany-browser
    - dosfstools
    - mtools
    - gparted
    - deborphan
    - pdftk
    - borgbackup
    - foliate
    - calibre
    - htop
    - neofetch
    - keepass2
    - gimp
    - inkscape
    state: present
  become: true
- name: "Install programming utilities"
  ansible.builtin.apt:
    name:
    - dconf-editor
    - emacs
    - python-is-python3
    - python3-pip
    - python3.11-venv
    - ack
    - fd-find
    - texlive-full
    - latexmk
    - pandoc
    state: present
  become: true
- name: "Remove image magick security policy for eps"
  ansible.builtin.lineinfile: 
    dest: /etc/ImageMagick-6/policy.xml 
    regexp: '^(.*)<policy domain="coder" .* pattern="EPS" />' 
    line: '  <policy domain="coder" rights="read|write" pattern="EPS" />' 
    state: present 
    backup: yes
  become: true
- name: "Remove image magick security policy for pdf"
  ansible.builtin.lineinfile: 
    dest: /etc/ImageMagick-6/policy.xml 
    regexp: '^(.*)<policy domain="coder" .* pattern="PDF" />' 
    line: '  <policy domain="coder" rights="read|write" pattern="PDF" />' 
    state: present 
    backup: yes
  become: true
