---
- name: "Install sway"
  ansible.builtin.apt:
    name:
    - sway
    - swaylock
    - rofi
    - i3status
  become: true

- name: "Create sway config directory"
  ansible.builtin.file: 
    path: ~/.config/sway
    state: directory

- name: "Configure sway"
  ansible.builtin.file:
    src: "{{playbook_dir}}/roles/debian/files/sway/config"
    dest: ~/.config/sway/config
    state: link

