---
- name: "Install VS Codium -- not sure if the repository is added by default"
  ansible.builtin.apt:
    name: codium
  become: true

- name: "Create Codium config directory"
  ansible.builtin.file: 
    path: ~/.config/VSCodium/User
    state: directory

- name: "Configure VS Codium"
  ansible.builtin.copy:
    src: vs_codium/settings.json
    dest: ~/.config/VSCodium/User/settings.json
    backup: true

